include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 350

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    unnecessary_this: true