import 'dart:ui';

class AppColor {
  AppColor._();

  static const wikiXMNavy = Color(0xFF0B1F33);
  static const backgroundDark = Color(0xFF061122);
  static const darkCardColor = Color(0xFF0c1c32);
  static const darkBorderColor = Color(0xFF314968);
  static const primaryNavy = Color(0xFF0D2B5E);
  static const headingColor = Color(0xFF102AA3);
  static const textColor = Color(0xFF3038C0);
  static const communityGreen = Color(0xFF2E7D4F);
  static const darkGreen = Color(0xFF07663B);
  static const intelligencePurple = Color(0xFF5B2CCB);
  static const civicBlue = Color(0xFF2563EB);
  static const darkBlue = Color(0xFF0046F9);
  static const successGreen = Color(0xFF16A34A);
  static const warningAmber = Color(0xFFF59E0B);
  static const alertRed = Color(0xFF8D1719);
  static const environmentalTeal = Color(0xFF0F766E);
  static const primaryInk = Color(0xFF101828);
  static const slate = Color(0xFF475467);
  static const mutedGray = Color(0xFF93a89f);
  static const mutedGrayLight = Color(0xFF697588);
  static const borderGray = Color(0xFFE4E7EC);
  static const softBackground = Color(0xFFF7F9FC);
  static const white = Color(0xFFFFFFFF);
  static const black = Color(0xFF000000);
  static const transparent = Color(0x00000000);
  static const primaryNavyNew = Color(0xFF05234b);
  static const primaryGreen = Color(0xFF118A3B);
  static const accentBlue = Color(0xFF1E88E5);
  static const lightGreen = Color(0xFFE6F4EA);
  static const background = Color(0xFFF6F8FB);
  static const textPrimary = Color(0xFF1D2433);
  static const textSecondary = Color(0xFF6B7280);
  static const borderDivider = Color(0xFFE5E7EB);
  static const success = Color(0xFF22C55E);
  static const warning = Color(0xFFF59E0B);
  static const error = Color(0xFFEF4444);
  static const darkGreenWeather = Color(0xFF83e2a0);
  static const darkGreenWeatherCard = Color(0xFF153928);
  static const darkGreenSportsCard = Color(0xFF0c211a);
  static const darkGreenSportsBorder = Color(0xFF223e35);
  static const darkGreenSportsBackground = Color(0xFF081410);
  static const sportsLightBackground = Color(0xFFF4F8F6);
  static const sportsLightCard = Color(0xFFFFFFFF);
  static const sportsLightBorder = Color(0xFFDCE8E1);
  static const sportsLightPrimaryText = Color(0xFF10251B);
  static const sportsLightSecondaryText = Color(0xFF0c8a49);
  static const darkGreenSportsPrimaryText = Color(0xFFFFFFFF);
  static const darkGreenSportsSecondaryText = Color(0xFF0c8a49);
  static const sportsBorder = Color(0xFFeed596);
  static const sportsDarkBorder = Color(0xFF636437);
  static const sportsActiveCard = Color(0xFFfffaf0);
  static const sportsActiveColor = Color(0xFF84610a);
  static const townHallGreen =  Color(0xff0d6b3f);
  static const townHallGreenDark =  Color(0xFF62D99B);

  static const garageRedSoft = Color(0xFFFFF0F1);
  static const garageSurface = Color(0xFFFFFFFF);
  static const garageDarkRedSoft = Color(0xFF48242B);
  static const garageDarkSurface = Color(0xFF0B2035);
  static const garageGreen = Color(0xFF087C4B);
  static const garageGreenDeep = Color(0xFF05633B);
  static const garageGreenSoft = Color(0xFFE8F7EF);
  static const garageGreenDark = Color(0xFF64D9A2);
  static const garageGreenDeepDark = Color(0xFF45BF86);
  static const garageGreenSoftDark = Color(0xFF123D36);
}